---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webhook.roldyx.duckdns.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: github-eventsource-svc
            port:
              number: 12000
              
