apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webhook
  namespace: argo-events
spec:
  rules:
  - host: webhook.roldyx.duckdns.org
    http:
      paths:
      - path: /
        backend:
          serviceName: github-eventsource-svc
          servicePort: 12000
